### ISSUE TITLE
Missing OSS from main help

### ISSUE THREAD

**Issue by ulsa** [aliyun/aliyun-openapi-meta#2]
There is no mention of the product 'oss' when running `aliyun help`. However, `aliyun oss` succeeds, so clearly it is a valid product. Looking in the `products.json` file in this repository, it is indeed missing. Maybe info on `oss` should be added to it?

Another thing: Perhaps this an issue for the `aliyun-cli` repo, but running `aliyun oss` shows there is a typo in the help text, where `aliyun` is written twice:

```
Usage:
  aliyun aliyun oss [command] [args...] [options...]
```

**Comment by JacksonTian** [comment]
For some reasons, the OSS is not same as other products, so the `oss` is not in products.json.

Thank you for the typo suggestion. We will fix it asap.

**Comment by JacksonTian** [comment]
We fix this issue in https://github.com/aliyun/aliyun-cli/pull/110 . Thanks again.
