### ISSUE TITLE
cr/GetAuthorizationToken has two parameters: InstanceId & RegionId

### ISSUE THREAD

**Issue by cofyc** [aliyun/aliyun-openapi-meta#23]
https://help.aliyun.com/document_detail/145324.html

however, this meta repo does not contain them:

https://github.com/aliyun/aliyun-openapi-meta/blob/9ce1f8ae486d76f0fc92a33082b764e73d5bf955/cr/GetAuthorizationToken.json#L1-L7

**Comment by JacksonTian** [comment]
It has been fixed.
